### ISSUE TITLE
Error reading input stream & Error opening URL input stream

### ISSUE THREAD

**Issue by angelofdev** [ksafin/DynamicEconomy#1]
http://pastebin.com/hysDV7yK

I've noticed when a few players join the server there is massive lag & this error is always followed.

**Comment by ksafin** [comment]
Seems like my update server was down, and it couldn't access the file to check if there's an update.

For the future, I've added a new config option in v .7.1 called "enable-update-checker".

If set to false, it will disable /hasupdate and /dyneconupdate, and will not check for updates upon player login.

If this error ever persists or occurs, set this field to false until I get the server back online.
