### ISSUE TITLE
Please add multiword support.

### ISSUE THREAD

**Issue by toxuin** [ksafin/DynamicEconomy#10]
I think title says it all. For now players can buy and sell items in all worlds - the only restriction is coordinates.
We have a dedicated world for trading so we really need the multiword feature. We use Multiverse for multiworld.

**Comment by ksafin** [comment]
Great Idea!
I'll definitely look into how that's coded and let you know if I can do it, but I'm pretty optimistic about it.

**Comment by ksafin** [comment]
MultiWorld support has been added;

It'll be released in v .8.0
