### ISSUE TITLE
BUCKET to "BUKKET" Issue

### ISSUE THREAD

**Issue by JamesNorris** [ksafin/DynamicEconomy#104]
When typing /buy bucket, I noticed that it says it sells you a "bukket" for 0.0, and then an item appears in items.yml called BUKKET, with only a buytime and selltime. I've checked my spelling and config, and even updated, and still this bug happens.

**Comment by ksafin** [comment]
Are you using the latest DE version, v .8.53?

**Comment by EmpathDemon** [comment]
this appears to be fixed in 8.6

**Comment by JamesNorris** [comment]
Yes, updated today, and deleted my old DE file. 

-It may be that I haven't updated the Items file, Ill try that and write back

**Comment by JamesNorris** [comment]
Okay, so I've tried a few things:
- Reloaded the folder
- Disabled all other plugins except for the dependencies
- Re-updated 8.53

EDIT: Figured it out, when I was going through the .jar file, I edited the defaults by mistake. Sorry for wasting your time!

**Comment by ksafin** [comment]
It's all good! :)
