### ISSUE TITLE
Enchanting items gives you levels

### ISSUE THREAD

**Issue by phobiac** [ksafin/DynamicEconomy#108]
I am not sure if this is due to just this plugin, or this plugin in combination with others, but a user reported that they were able to enchant an item and receive levels for doing so. I do not have exact numbers, but she enchanted a diamond chestplate at level 25 and went UP to level 30 or so afterwards. This was repeatable with other items and stopped when I disabled the current (.8.6) version of the plugin.

**Comment by ksafin** [comment]
Did this user use DynamicEconomy to purchase/sell EXP before enchanting? Currently there's a bug that, if you buy/sell EXP, and then enchant an item, any EXP you bought or sold will return to you.

It's got something to do with bukkit commands that aren't working properly with EXP, but I'm looking into it.

**Comment by phobiac** [comment]
No, this was at an enchanting bench (which makes it all the stranger). I confirmed it was this plugin by disabling it, enchanting, and re-enabling it, and this only occurred with the plugin active. It also seems to be something that's changed in the last two updates or so as this was not occurring before.

It's possible that the bukkit issue you mentioned is the root cause. Especially considering it happens at an enchanting bench.

**Comment by phobiac** [comment]
Also, because I just realized I didn't properly answer, the user did not buy or sell experience. I believe I have that disabled but I will double check.

**Comment by phobiac** [comment]
The user was also getting seemingly random amounts of experience back after each enchant.

**Comment by ksafin** [comment]
Fixed!

**Comment by phobiac** [comment]
I know this is closed, but what can I do to get the fix? Wait for the next version? (I am okay with doing this).

**Comment by ksafin** [comment]
Correct.

**Comment by phobiac** [comment]
Fair enough, thank you for the plugin. :)
