### ISSUE TITLE
Feature Request: Multiple banks

### ISSUE THREAD

**Issue by numinit** [ksafin/DynamicEconomy#113]
I think multiple banks would be a good feature for Dynamic Economy. It would encourage competition among banks for large servers.

Thanks!

**Comment by ksafin** [comment]
What do you mean?

DE doesn't use banks, it just stores taxes & interest in one bank, which is supposed to be a "government" bank

**Comment by numinit** [comment]
Maybe I commented too quickly after setting up the plugin.

Let's say a group of players (or admins, for that matter) wants to set up their own bank. They're bound to the server interest rate (which is controlled by the administrators) but can manage bank accounts for other players and loan out money (provided that the bank is actually solvent themselves).

What I'm saying is that there should be nothing stopping players from forming their own bank, provided that they have the money to pay interest on people's accounts and the money to give out loans.

I hope this is a little more clear. It would be a cool feature.

**Comment by ksafin** [comment]
Hmm not really, for several reasons..

1) DynamicEconomy doesn't handle banks. At all. It does absolutely nothing with banks besides deposit interest rate payments and tax revenues.

2) Loans are taken out of the global economy, not from a players bank

**Comment by numinit** [comment]
Fair enough. I'll close this issue. It was worth a shot.
