### ISSUE TITLE
Prices

### ISSUE THREAD

**Issue by Kelnoc** [ksafin/DynamicEconomy#18]
Hi,

i noticed that, if i buy/sell suff, the transaction uses the new price. Doesnt it make more sense, if the price changes after the deal?

Otherwise, i really love your plugin =)

Greetings,
Kelnoc

**Comment by ksafin** [comment]
It doesn't REALLY use the newprice.

It uses the initial price, the final price, and every price in between.

The price is constantly changing during the transaction; so if you buy 50 stone, it uses 50 different prices (1 price for every stone).
