### ISSUE TITLE
/sell <item> all now leaves 1 in inventory, and still gives money

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#20]
I am using the latest version. v .8.03 for CB 1.2.3-R0.2 and this CraftBukkit version: http://dl.bukkit.org/downloads/craftbukkit/view/00923_1.2.3-R0.3/

this is affecting all items. Simply get one item in your inventory, then /sell <item> all -- you are still given money and the item is not removed from your inventory. Edit: Also, if you have 64+ of the item in your inventory all but 1 is sold.

**Comment by angelofdev** [comment]
I'm also having this issue on version .8.03

**Comment by ksafin** [comment]
Fixed the issue, v .8.04 incoming.
I had some odd statement that decremented the saleAmount when the user uses keyword "all".

I think there was a point in time that the bukkit build was unstable and the method I used for counting items in inventory always returned one too little or too much, leading me to add or subtract 1 from various item amounts.

Seems like it's all good now.
