### ISSUE TITLE
Using /sell on items with multiple types

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#22]
Let's use an example here. The original issue where Wool was not removed from your inventory when selling Orangewool, appears to be fixed. The new issue is now you could for example, type /sell orangewool and it will sell and give you money even if you don't have that item! 

This bug appears to affect any 'multiple type' item IDs. For example, you could /sell yellowink despite not having any ink. You could /sell wood despite not having any. I found that I could sell any wood type despite not having any in my inventory. I tested both wool, wood, and ink. They all seems to be affected by this bug so I am guessing it will also affect any other items with multiple types. What I mean by mutliple types is: 17:1, 17:2, 17:3, 17:4 etc. (or in the config file 17001, 17002, 17003, etc.). Another thing I noticed is that you can not specify more than one of said item. For example, /sell wood will give you money but /sell wood 2 will give the proper "You do not have 2 wood" message.

I did find that all of the single type items I tried to /sell without them in my inventory worked as expected. For example, /sell ironingot returned the proper "You do not have 1 iron ingot"

**Comment by ksafin** [comment]
Fixed - v .8.05
