### ISSUE TITLE
/sell <item> all still slightly bugged

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#23]
There is one last bug I noticed with /sell <item> all -- When you type /sell <item> all it will still give the sell dialog despite nothing be sold.

For example, /sell wool all when you have no wool in your inventory returns:
You sold 0 of WOOL - 0.0% tax = $0.0 Total
New Price of WOOL is $0.1 (0.0)
Sale success!

Not sure if this is even possible to fix, but if so it should return:
You do not have any <item> to sell.

(or something along those lines)

**Comment by ksafin** [comment]
I'll definitely fix it with v .8.1

I'm releasing a new feature, which is my priority right now.

**Comment by ksafin** [comment]
Fixed in v .8.1
