### ISSUE TITLE
Pinewood and Birchwood small bug

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#25]
BIRCHWOOD:
  velocity: 0.05
  id: 17002
  price: 0.1
  floor: 0.1
  ceiling: 1
  description: Part of a tree!
  stock: 114
  spread: 0.05
  time: 0
PINEWOOD:
  velocity: 0.05
  id: 17001
  price: 0.1
  floor: 0.1
  ceiling: 1
  description: Part of a tree!
  stock: 114
  spread: 0.05
  time: 0

The ID in game for Birchwood is 17:2 and the ID for Pinewood is 17:1. If you type /sell 17:1 or /sell 17:2 -- both of these commands sell Birchwood. /sell pinewood correctly takes from your quantity of pinewood. Note that /buy 17:1 and /buy 17:2 both work as expected.

**Comment by ksafin** [comment]
Works properly on my server, I can't seem to replicate.

/sell 17:2 correctly sells pinewood, /sell 17:1 correctly sells birchwood.
Both give a message about the wood being absent if you don't have it, regardless of whether you have the other.

I know these two are switched around (17:2 should be pinewood, but it's birch, & vice versa) but is there an issue besides this?

**Comment by jayyx2** [comment]
I am actually having trouble replicating this now too -- aside from the issue you mentioned it seems fine. Ticket can be closed.
