### ISSUE TITLE
You can not buy/sell all types of saplings

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#26]
SAPLING:
  velocity: 0.01
  id: 6
  price: 0.2
  floor: 0.01
  ceiling: 0.45
  description: A small plant
  stock: 50
  spread: 0.01
  time: 0

Currently there is only one sapling listed in the items.yml. There are 4 types of saplings total in-game, we should be able to buy/sell all of them. I did notice that in previous versions, /sell 6:3 /sell 6:2 and /sell 6:1 worked to sell sapling but did not take stock of any of these items. This was fixed in one of the recent releases, which is good. But in any case, I'd like to be able to buy/sell all of the items as necessary.

The Item IDs and names are as follows:
6 Sapling
6:1 Redwood Sapling
6:2 Birch Sapling
6:3 Jungle Sapling

**Comment by ksafin** [comment]
Added
