### ISSUE TITLE
/sell hand does not remove stock, but gives money

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#29]
/sell hand command works to give you money for what you have in your hand, which is great. However, I tested with mutliple different items/quantities and the command always gave money but _NEVER_ took away from any of the quantities.

Example:
1 leather in hand. /sell hand -- Received money but quantity stayed at 1 leather
64 cobble in hand /sell hand -- Received money for 64 cobble, but quantity stayed at 64

**Comment by ksafin** [comment]
Fixed, forgot to add code to remove item from hand.
