### ISSUE TITLE
NPE Spam with fresh .7 install

### ISSUE THREAD

**Issue by Bronski** [ksafin/DynamicEconomy#3]
This comes up every 10 seconds or so:

```
08:06:08 [SEVERE] java.lang.NullPointerException
08:06:08 [SEVERE]       at me.ksafin.DynamicEconomy.loan.run(loan.java:255)
08:06:08 [SEVERE]       at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
08:06:08 [SEVERE]       at java.lang.Thread.run(Unknown Source)
```

I removed the old plugin folder and let a new one generate, same thing.

CB1938.

**Comment by ksafin** [comment]
Fixed; Thread accessing and checking for overdue loans was getting null because no loans were taken out.

Fixed by having a check for null before continuing; also, if you set use-loans to false, the thread to check for loans will never run or instantiate.

Out in v .7.1
