### ISSUE TITLE
Add permission nodes for certain items

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#31]
If possible, could we add permission nodes for certain items? For example, by editing config.yml with each item having Permission: true/false -- could we then use dynamiceconomy.item.cobble to grant that rank permission to buy?

**Comment by mashlol** [comment]
Would love to see this happen :)

**Comment by Neodork** [comment]
Yes that would be nice, so when you put Permission: true all items need to be specified for certain groups

**Comment by ksafin** [comment]
Done in latest version ( v .8.6) via ItemGroups
