### ISSUE TITLE
[Misstype]? PINESAPLING

### ISSUE THREAD

**Issue by Malaras** [ksafin/DynamicEconomy#33]
in items.yml
There is 2? might be a reason, but wasn't sure so figured id send a ticket.

PINESAPLING:
  velocity: 0.01
  id: 6002
  floor: 0.01
  ceiling: 0.45
  description: A small plant
  stock: 50
  spread: 0.01
  time: 0
PINEESAPLING:
  price: 0.2

**Comment by ksafin** [comment]
Fixed. Accidentally added an E to one of them.
