### ISSUE TITLE
[Suggestion] Banking / Loaning part of your plugin

### ISSUE THREAD

**Issue by JoneKone** [ksafin/DynamicEconomy#34]
Once I suggested this to YouLoad maker jeroende2e. And I will now just copy paste.

Why? Cos I think this would be a much better plugin to have this feature + jeroende2e don't want to dev plugins anymore :(

"

Maby a bank kind of system that a player can setup..

Put money in your bank.. A Cuboid Bank where you must go to actually get the loan..

A player walks in, then sets command /youloan loan (get loan)
Youloan scans the world guard registery and finds this players land that he owns (single owner on a world guard cuboid).

prints a list

"Hello player, these are your owned lands"
"1. x -100 z 200 y 30 <- maby the centter of the cuboid, size of land 400x200x128"
"Would you like to pawn this area?"
"/yes"

Bank owner gets a message when he log in.
"Hello mr bank, these guys want to loan money from you"
"Player: x-100 z 200 y 30 (size)" This area is near Zone 1.
"Would you like to loan money for player"
"/yes" ( sets the cuboid protection under new ownership the bank or all the owners of the bank, /region removeowner spawn_park player /region addmember spawn_park player /region addowner spawn_park the_big_bad_bank)
"/no"

Zones:

The mr bank can set zones for he's bank
Zone 1 cuboid (spawn area)
Zone 2 cuboid (in a town called very rich ppl)
zone 3 cuboid everything else (don't show me these places) (deny the loan instantly when player wants to pawn it)

This is my very first draft of what I would like to see.. And I know this means that the area has to be bought before you can apply for the loan.

edit
Why put money to the bank!? cos many ppl can own One bank..

If interests are not payed in due time. Player can forfeit the area.

"

**Comment by ksafin** [comment]
This is probably out of the scope of DynamicEconomy.

I may eventually make a similar system, but only as an extension of DE, it'll be a separate plugin. This deviates too much from DE's central purpose.

**Comment by JoneKone** [comment]
Thx for answering :) an addon. that would be cool

What i'm promoting here is... Well MC is a build a house/building/bank game What I would like to see in all plugins/mods that it will incorporate the actual building in to everything.. It's pointless to have a Bank if you can do your banking Anywhere in the world..
