### ISSUE TITLE
Small issue with /unbanitem

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#35]
If you type just /unbanitem, it says 'Wrong Command Usage. /banitem [Item] [sale|purchase] instead of /unbanitem [Item] [sale|purchase]

**Comment by jayyx2** [comment]
Not a big deal, but this should be an easy fix if I am not mistaken =)

**Comment by ksafin** [comment]
Fixed. It was calling unbanitem correctly, I just forgot to change the Incorrect-Args response to /unbanitem instead of /banitem since I copy and pasted it from the /banitem code.
