### ISSUE TITLE
Optional lower limit on damage price reduction

### ISSUE THREAD

**Issue by gjdawson** [ksafin/DynamicEconomy#36]
Hi again.

I have a little issue with the way you're currently calculating the amount paid out for damaged tools. Once they get past a certain point, dyneamiceconomy states that the player doesn't have the tool they're trying to sell. I've got a couple of players who were saving up their damaged tools so they could sell them off for a token amount rather than just wasting them.

I understand the whole "infinite tool" issue but I don't personally have a problem with players doing that, as I've set up prices so they have to earn a lot of money before they can buy new and also set up a blacksmith who is cheaper to use than buying new tools. I'd like, if it's possible, to have some way of setting dynamic economy to pay out a minimum scrap value for tools and weapons rather than the current system.

**Comment by ksafin** [comment]
I don't think that'll happen.

The majority of users love this system; I'll just fix the bug where DE is telling them they don't have the item

**Comment by gjdawson** [comment]
Fair enough I suppose. I've set up my own scrap merchant with a citizens NPC, in case anyone else has a similar idea.
