### ISSUE TITLE
1.1R4 DynamicEconomy 7.3 ERROR

### ISSUE THREAD

**Issue by etherz10** [ksafin/DynamicEconomy#4]
25.02 22:19:43 [Server] INFO    at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
25.02 22:19:43 [Server] INFO    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:435)
25.02 22:19:43 [Server] INFO    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:503)
25.02 22:19:43 [Server] INFO    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
25.02 22:19:43 [Server] INFO    at com.bergerkiller.bukkit.nolagg.logging.TimedWrapper.run(TimedWrapper.java:17)
25.02 22:19:43 [Server] INFO    at me.ksafin.DynamicEconomy.DynamicEconomy$1.run(DynamicEconomy.java:367)
25.02 22:19:43 [Server] INFO    at me.ksafin.DynamicEconomy.loan.dynamicInterest(loan.java:288)
25.02 22:19:43 [Server] INFO    at java.lang.Double.valueOf(Double.java:492)
25.02 22:19:43 [Server] INFO    at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1242)
25.02 22:19:43 [Server] INFO java.lang.NumberFormatException: For input string: "ï¿½"
25.02 22:19:43 [Server] WARNING Task of 'DynamicEconomy' generated an exception

**Comment by ksafin** [comment]
Fixed in v .7.4
