### ISSUE TITLE
Permissions for Specific Items

### ISSUE THREAD

**Issue by mashlol** [ksafin/DynamicEconomy#40]
I wish to create an economy where certain players will be able to buy/sell certain items, and others will not.

Right now all there is is "dynamiceconomy.buy".  It would be great to have something like dynamiceconomy.buy.stone, or dynamiceconomy.buy.1.  For regular functionality dynamiceconomy.buy.\* would be used.

**Comment by jayyx2** [comment]
I already opened a ticket for this: https://github.com/ksafin/DynamicEconomy/issues/31

**Comment by mashlol** [comment]
Fair, this can be closed as duplicate then :)

**Comment by jayyx2** [comment]
Mashlol, you could actually close this on your own I believe
