### ISSUE TITLE
/sell bow gives money, leaves the bow in inventory

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#41]
Typing /sell bow gives money, but leaves the bow in inventory.

**Comment by jayyx2** [comment]
Update: selling a bow works. Selling an enchanted bow leaves the bow in the inventory and still gives money.

**Comment by ksafin** [comment]
I'll make enchant-appropriate code before .9

**Comment by ksafin** [comment]
There's a second ticket with this info, closing this to avoid duplicates.
