### ISSUE TITLE
[Dynamicsigns] Redwool, Blackwool, Bluewool

### ISSUE THREAD

**Issue by Neodork** [ksafin/DynamicEconomy#45]
I love the new signs they make the economy easy read able. Keep on the good work!

The following signs did not react: Redwool,Blackwool,Bluewool
Example:
Line1: Dynamicsign
Line2: BLUEWOOL
Line3: Velocity

Line1: Dynamicsign
Line2: 17:11
Line3: Velocity

Both won't be seen as dynamicsign

**Comment by Warhawker** [comment]
Same goes for "diamond"
"pumpkinseed"

Only a select few do not work.

**Comment by Neodork** [comment]
No becuase for diamond and pumpking seed you will just use the original names (I have them working)

**Comment by Neodork** [comment]
Woeps misclicked.

**Comment by Warhawker** [comment]
The original names are...

**Comment by Kyton** [comment]
Wood doesn't work either, i.e.

Line 1: dynamicsign
Line 2: wood
Line 3: price

**Comment by ksafin** [comment]
All of this works for me in the latest version.

Submit another ticket if it isn't the case.
