### ISSUE TITLE
/buy experience bug discovered

### ISSUE THREAD

**Issue by jayyx2** [ksafin/DynamicEconomy#46]
Works to buy/sell just fine.

However, if you buy experience  then enchant an item, and then buy experience again -- it will return you to the level you were before enchanting the item.

**Comment by ksafin** [comment]
I'll check it out.

**Comment by jayyx2** [comment]
This should be high priority IMO

**Comment by ksafin** [comment]
There's multiple tickets for this issue, and while it is being worked on, I'm closing duplicate tickets.
