### ISSUE TITLE
Permissions Ignored with PEX

### ISSUE THREAD

**Issue by DaneEveritt** [ksafin/DynamicEconomy#47]
Permissions are being ignored with PEX meaning anyone can change prices and such.

Also: /buy diamond 0 gives a free diamond.

**Comment by ksafin** [comment]
Shouldn't be; Others are using PEX fine. Although the 1.2.4 update could have screwed up PEX.

**Comment by NotYetRated** [comment]
PEX not working for me either on 1.2.4, nor did it work on 1.2.3... ALL users has access to ALL commands.

**Comment by ksafin** [comment]
Try to use PEX negative nodes to deny users permissions.

**Comment by ghost** [comment]
I had to do this as well, and using wildcard permissions didn't work, I had to use negative nodes for each command I wanted to disable.

**Comment by ghost** [comment]
And the update commands don't appear to respect permissions at all. I put the following in the permissions file, but a normal player could execute these commands:
    - -dynamiceconomy.dyneconupdate
    - -dynamiceconomy.hasupdate

**Comment by ksafin** [comment]
What's the status with this issue? Still a problem?

**Comment by ksafin** [comment]
Closed due to no response, may be re-opened if response is met, I can't seem to reproduce the error.
