### ISSUE TITLE
A few bugs

### ISSUE THREAD

**Issue by mzx987** [ksafin/DynamicEconomy#5]
1. It will not let you buy or sell in the region even though it is defined.
2. When you stop the server, it clears everything in your items.yml file.
3. If you have birch or dark wood and try to /sell wood, it will give you the money for selling it, but it will not erase the dark/birch wood in your inventory (It may do the same with items that have the same ID.)

(These are the only ones I could find so far. If you find any more bugs, please post a comment on this issue.)

**Comment by ksafin** [comment]
1) Fixed. Either I can't replicate the error or I fixed the problem by fixing some other bugs.

2) Also fixed, same reason as #1.

3) Fixed. Added all-encompassing data-value sales/purchases for birchwood, pinewood, and junglewood (for 1.2). These three items now exist in items.yml under the "WOOD" data.
