### ISSUE TITLE
[feature] price-inflation-over-time if no /sells happen over time. 

### ISSUE THREAD

**Issue by quickclay** [ksafin/DynamicEconomy#54]
This is the opposite of the price-decay-over-time, and would extremely useful for servers like mine that let players /sell their loot to the server, but still have to buy things from player and server shops.  Without this, the price would only go down over time and never go up without access to the /buy command.

**Comment by Neodork** [comment]
Random events ?

**Comment by quickclay** [comment]
Random events aren't tied to players buying or selling habbits, if you were suggesting this as an alternative.  I would like a way for prices to slowly rise over time until they are sold, subject to the ceiling.

**Comment by Neodork** [comment]
To make the price go up when no one insn't actually buying it, that makes no sense...

**Comment by quickclay** [comment]
When no one's SELLING it.

**Comment by ksafin** [comment]
Price Inflation has been added!
