### ISSUE TITLE
Buying over 64 glitch

### ISSUE THREAD

**Issue by Spiritwo** [ksafin/DynamicEconomy#55]
If i type /buy log 70, it gives me a stack of 70 log and then a separate stack of 6 log, even though I only paid for 70 logs. I'd assume it has to due with the fact that 70 is 6 more than 64 (the normal max stack size). If I were to buy 80 instead of 70, then it gives me a stack of 80 logs, and a separate stack of 16 log. Again I'd assume this is because 80 is 16 more than 64. So basically, people can just buy more than 64 at a time and get extra for free.

**Comment by Fogest** [comment]
Seems like it should be an easy fix. It just needs to put it into another inventory slot if the total amount they are buying is greater then 64.

**Comment by ksafin** [comment]
It's correctly giving me a stack of 64 and a stack of 6. Do you still have this issue?

**Comment by Fogest** [comment]
I'd assume it's fixed.

**Comment by ksafin** [comment]
Ok, well I didn't implement any code that changes the performance of this; it never gave me over 64 of anything. 

So if it works for you now, it's a miracle :P
