### ISSUE TITLE
loan problem :)

### ISSUE THREAD

**Issue by BONNe** [ksafin/DynamicEconomy#56]
15:27:16 [SEVERE] java.lang.NullPointerException
15:27:16 [SEVERE]       at couk.Adamki11s.Extras.Colour.ExtrasColour.sendColouredMessage(ExtrasColour.java:17)
15:27:16 [SEVERE]       at me.ksafin.DynamicEconomy.loan.run(loan.java:371)
15:27:16 [SEVERE]       at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:126)
15:27:16 [SEVERE]       at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:520)
15:27:16 [SEVERE]       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:452)
15:27:16 [SEVERE]       at net.minecraft.server.ThreadServerApplication.run(SourceFile:490)

**Comment by ksafin** [comment]
Are you still getting this bug?

**Comment by BONNe** [comment]
hmm, i havnt use loan after this, i will check as soon as possible

**Comment by BONNe** [comment]
Yes The same problem appers in 8.5

**Comment by ksafin** [comment]
Fixed
