### ISSUE TITLE
Empty Files

### ISSUE THREAD

**Issue by etherz10** [ksafin/DynamicEconomy#6]
All the files are empty, the config,items,loans are all blank - 1.1R4

6.02 00:38:45 [Server] INFO [DynamicEconomy] CommandExec Permissions set
26.02 00:38:45 [Server] INFO [DynamicEconomy] CommandExec Economy set
26.02 00:38:45 [Server] SEVERE  at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
26.02 00:38:45 [Server] SEVERE  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:408)
26.02 00:38:45 [Server] SEVERE  at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
26.02 00:38:45 [Server] SEVERE  at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:344)
26.02 00:38:45 [Server] SEVERE  at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:357)
26.02 00:38:45 [Server] SEVERE  at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:182)
26.02 00:38:45 [Server] SEVERE  at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:199)
26.02 00:38:45 [Server] SEVERE  at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:380)
26.02 00:38:45 [Server] SEVERE  at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
26.02 00:38:45 [Server] SEVERE  at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:230)
26.02 00:38:45 [Server] SEVERE  at me.ksafin.DynamicEconomy.DynamicEconomy.onEnable(DynamicEconomy.java:221)
26.02 00:38:45 [Server] SEVERE  at me.ksafin.DynamicEconomy.Initialize.setConfig(Initialize.java:53)
26.02 00:38:45 [Server] SEVERE  at org.bukkit.configuration.file.FileConfiguration.save(FileConfiguration.java:49)
26.02 00:38:45 [Server] SEVERE java.lang.IllegalArgumentException: File cannot be null
26.02 00:38:45 [Server] INFO java.lang.IllegalArgumentException: File cannot be null
26.02 00:38:45 [Server] INFO [DynamicEconomy] Error saving config
26.02 00:38:45 [Server] INFO [DynamicEconomy] Loans database loaded.
26.02 00:38:45 [Server] INFO [DynamicEconomy] Region database loaded.
26.02 00:38:45 [Server] INFO [DynamicEconomy] Items database loaded.
26.02 00:38:45 [Server] INFO [DynamicEconomy] Vault Permissions hooked
26.02 00:38:45 [Server] INFO [DynamicEconomy] Vault Economy hooked
26.02 00:38:45 [Server] INFO DynamicEconomy v.7.3 by kSafin (Kirill Safin) enabled!
26.02 00:38:45 [Server] INFO [DynamicEconomy] Loading DynamicEconomy v.7.3.

**Comment by ksafin** [comment]
Fixed;

Used new method to set file & config objects within the Initialize class.

Will be uploaded with v .7.4
