### ISSUE TITLE
Items.yml reseting even with Stone

### ISSUE THREAD

**Issue by ghost** [ksafin/DynamicEconomy#62]
I deleted few stuff like Goldore, diamondore , tnt , gunpowder. Stuff like that but i left Stone.

Even tho Stone is there it is resetting like a mad person.

I also have tried adding all the deleted ones back . But no use. It still resets.

**Comment by Neodork** [comment]
Yea, that's because you can't make changes into the item file. Use ingame commands and the config file, it says you can, but haven't got it to work yet.

**Comment by toxuin** [comment]
Seems like it is a bug. The file is in ANSI by default and resetting each server restarts. Magic begins: convert it to UTF-8 without BOM and it saves! Thus, you have to have all the items in it. You can't leave just few you want to be tradable. You have to ban all other items (that's a lot!).

**Comment by ksafin** [comment]
I haven't gotten the problem to replicate.

It seems, so far, that it's server specific.

Some servers have the file created with different specifications than others, kind of like what you mentioned between ANSI and UTF-8.

Depending on how the server sets up the file, Items.yml will save or not save.
