### ISSUE TITLE
[Bug] Iron Pickaxe selling at the floor price, not the current price.

### ISSUE THREAD

**Issue by phobiac** [ksafin/DynamicEconomy#64]
When doing a /sell ironpick on an iron pick, the plugin gives a player an adjusted amount (adjusting due to durability) based off of the FLOOR price and not the current price.

Ex.
I have the config set so that iron pickaxe has a floor of $30 and a ceiling of $170. When selling a new iron pick with the current prices at $170, I get $30 for some reason.

**Comment by phobiac** [comment]
This seems to happen with a few other items as well, I had a user sell upwards of 10 lapis lazuli and get the floor price for all of them instead of the reported price x10.

**Comment by ksafin** [comment]
I get correct price for all items you're specifying.. are you still getting the bug?

**Comment by phobiac** [comment]
Yes, I'm still getting this. Maybe it is just that I'm expecting sales to work differently?

What's happening right now is when I sell a group of items, it almost seems like a bunch of individual sales occur. For example if lapis is at a price of 10 units with a floor of 9 units and I sell 10 lapis I am expecting to get 100 units but instead get slightly more than 90 units. What I thought was supposed to occur is something like:
current item price x number of items sold = returned units
price is then change by how many were sold

What seems to happen is something like
current item price x one item = returned units
price is changed
repeat until group is sold off
give total units to player

I'm sorry if that doesn't make much sense. Any information I can give just ask for it.

**Comment by phobiac** [comment]
For reference, I am using v8.5 and here is my config.yml

Use-Stock: false
Use-boundaries: true
prefix: ''
default-amount: 1
local-price-notify: true
global-price-notify: true
log-writing: true
salestax: 0.0
purchasetax: 0.0
deposit-tax-to-account: false
account-name: ''
location-restrict: false
minimum-y: 0
maximum-y: 256
alt-commands: false
enable-update-checker: false
use-regions: false
use-loans: false
use-static-interest: false
interest-rate: 0.05
dynamic-interest-rate: 0.05
dynamic-compression-rate: 22503.068881653293
payback-time: 20
max-num-loans: 1
max-loan-amount: 500
min-loan-amount: 10
use-loan-account: false
loan-account-name: ''
loan-check-interval: 300
banned-sale-items: 'Pistons,Stickypistons'
banned-purchase-items: ''
enable-over-time-price-decay: true
over-time-price-decay-percent: 0.05
over-time-price-decay-period: 1440
over-time-price-decay-period-check: 60
use-percent-velocity: false
dynecon-world: world1,world1_nether
currency-symbol: '&2o'
enable-random-events: true
random-event-interval: 100
random-event-chance: 0.05
sign-tagline-color: '&a'
sign-info-color: '&f'
sign-invalid-color: '&c'

**Comment by phobiac** [comment]
Also, here is the entry for lapis lazuli in items.yml (this occurs with every item though, as far as I can tell)

LAPISLAZULI:
  velocity: 0.8
  id: 351004
  price: 13.0
  floor: 9.0
  ceiling: 13
  description: Prettiest ore in the world
  stock: 50
  spread: 0.8
  time: 1333914764972

**Comment by ksafin** [comment]
Ah, I see.

Yeah, you're misinterpreting DE's price calculation engine.

The calculation isn't a simple price x quantity = total.

Reason?
Think about it like this
If you buy 10 items at a price of 10 units and a velocity of 1 unit, you'll pay (10 x 10 = 100), and the new price will be (10 x 1 = 10 + 10+ = 10.
So now, you spent 100, and the new price of the item is 20.
If you go and SELL those 10 that you just bought, that'd be (10 \* 20 = 200) where 10 is the number of items, and 20 is the new price.
So here you can see that from buying $100-worth, the price increased, and you sold back what you just bought at the new price of $20 to get an instant $100 profit.

DE's pricing engine prevents that.

Here's how it works, assuming the following conditions:
ITEM:
Price: 10
Velocity: 0.5
Floor: 5
Ceiling: 15

Lets say you buy 20 of this item.
The first of these 20 will cost 10, as you expect. The second will cost (10 + velocity, which is .5) so the second is 10.5. Likewise, the next will be 11 (10.5 + 0.5).

This keeps happening (each item is priced at (velocity + previous price) until a ceiling or floor is reached, at which point all items you still need to buy will be purchased at the ceiling.

So in this example, after buying 10 of the 20, the new price is 15, which is the ceiling. So the next 10 items will be bought at 15.

Hope that clears things up.

**Comment by phobiac** [comment]
So if I'd like to see less of a dramatic price change from just buying or selling 10 things, should I decrease the velocity? I will admit I hadn't thought about this as hard as you seem to have (which is good considering I didn't write the plugin). Sorry for the incorrect bug report.

**Comment by ksafin** [comment]
Right, velocity is the change per unit sold/bought, so a lower velocity means a less drastic change in price.
