### ISSUE TITLE
"This World does not have access to this command"

### ISSUE THREAD

**Issue by taksuyu** [ksafin/DynamicEconomy#67]
Its probably because I have a custom default world but turning dynecon-world off and not using regions still does not allow me to access it in any of my world.

**Comment by ksafin** [comment]
What do you mean turning dynecon-world off?
You cannot turn it off.

dynecon-world in config.yml is a world name, not a true/false value.
You must set this setting to the name of your world, which in config.yml by default will be "world"

I'm adding functionality for multiple worlds, though.
