### ISSUE TITLE
No Ores in Items.yml

### ISSUE THREAD

**Issue by etherz10** [ksafin/DynamicEconomy#7]
I use a plugin called protectionstones which uses coal, lapis & diamond ore blocks to create a personal protected zone and wanted for the players to be able to buy/sell them however i've realised that at this point in time DynEcon doesnt support them, can you add them please :D

**Comment by ksafin** [comment]
It'll be in v .7.7

**Comment by ksafin** [comment]
Already added to code - fully functional.
More things will be added, then this will be packed up and uploaded.
