### ISSUE TITLE
Velocity Percentages Break DynamicEconomy

### ISSUE THREAD

**Issue by Warhawker** [ksafin/DynamicEconomy#71]
Setting "use-percent-velocity: false"
To
"use-percent-velocity: true"

Will cause all items to buy and sell for $0. Though the plugin still makes the correct price changes, the price changes don't ever affect the real price of the item. It remains at 0 always.

Problem remains when all velocities in Items.yml are set: Defined Velocity < 1.0

**Comment by dejavecu** [comment]
I also have this problem.

**Comment by semibreve42** [comment]
I also have this issue.

**Comment by Bainon** [comment]
Same here. Same as Issue #77

**Comment by ksafin** [comment]
I believe this is fixed
