### ISSUE TITLE
Server Held On join request

### ISSUE THREAD

**Issue by Warhawker** [ksafin/DynamicEconomy#73]
The server is held for a few seconds whenever a player attempts to join.
DynEcon .8.5
Bukkit Rb 1.2.5

Testing was done to verify that it was Dynecon, and not other plugins, knocking off only one at a time, reloading the server, and having somone join, measuring any lag.

This is not a server issue, My cpu maxes out at 15% during the tests on a 3.6Ghz 4Gb RAM Dedicated machine.

8 players were online during testing.
11 other plugins were running.

**Comment by ksafin** [comment]
I'd assume this is because DE pings a web server to check for a DE update whenever a player with the permission joins.

While not a bug, this will definitely be in my plans for code optimization.
