### ISSUE TITLE
/sell inventory allows to sell banned items

### ISSUE THREAD

**Issue by dejavecu** [ksafin/DynamicEconomy#75]
If you put banned item in inventory and do /sell inventory, it will be sold and you will get money. 

Btw, can you update the sources? I want to test it due to another bugs.

**Comment by ObsceneNameHere** [comment]
This is also happening to me, So Confirmed. The most I can do for now is set the banned items price to zero

**Comment by ksafin** [comment]
Fixed in recent versions.
