### ISSUE TITLE
[Minor Bug] Pine and birch saplings are mixed up

### ISSUE THREAD

**Issue by phobiac** [ksafin/DynamicEconomy#79]
In items.yml, Pine saplings are listed as 6002 and birch as 6001. This is the opposite of what they should be, as you can find here:
http://www.minecraftwiki.net/images/8/8c/DataValuesBeta.png

**Comment by jayyx2** [comment]
You could fix this yourself in items.yml

**Comment by phobiac** [comment]
Yes, I did. I'm reporting the bug because... it is a bug.

**Comment by jayyx2** [comment]
Oh I wasn't saying not to report it, I was just saying you could also fix it until it is fixed in the plugin =)

**Comment by phobiac** [comment]
Yes, sorry. I didn't mean to be so defensive.

**Comment by EmpathDemon** [comment]
I tried fixing the item number in items.yml, but it doesn't fix the problem. Then I tried just swapping the names of the items, and that didn't work either. How do I fix this in items.yml?

**Comment by ksafin** [comment]
Don't change it in Items.yml, change it in alias.yml.

The new alias feature lets you change it around easily.

Find the existing aliases and modify them.
