### ISSUE TITLE
sell [item] all - not functioning correctly

### ISSUE THREAD

**Issue by angelofdev** [ksafin/DynamicEconomy#8]
The **/sell [item] all** doesn't seem to be functioning correctly. 

When players use **/sell [item] all** they receive a message saying;

eg. /sell gold all
_'You do not have 65 [item]'_

and for some random items

eg. /sell stick all
_'You do not have 1 [item]'_

Using DE v.7.6

**Comment by ksafin** [comment]
Fixed both; fix will be released in v .7.7
