### ISSUE TITLE
[Request] Disabling of certain item groups

### ISSUE THREAD

**Issue by phobiac** [ksafin/DynamicEconomy#80]
I know this is a large request, but would it be possible to have certain items in "groups" or even to define groups of items and then ban for sale/purchase based on group names? For example, it is a pain to ban all the varieties of potions. A "no buying potions" (but possibly selling) option would be nice. Items not obtainable normally (such as redstone ore) could be in a group.

I'd actually be willing to make multiple groups and work with you on deciding what should be in them if you are interested in doing this.

**Comment by phobiac** [comment]
Correction, redstone ore is obtainable but only with silk touch. Possibly it could just go in an "ore" group.

**Comment by ksafin** [comment]
I may eventually add this as a feature but it's not a priority as of now.

If I do end up adding it, the groups would be user-defined rather than defined by me; I'd only provide an example group.
