### ISSUE TITLE
/loan gives free money

### ISSUE THREAD

**Issue by ellox** [ksafin/DynamicEconomy#81]
I have an issue with the /loan option. Player can loan money with the command successfully. The problem is that  the loan just disappears and gives free money to the player if the player doesn't have sufficient amount of money to pay back. Log and chat print "[player] has been charged [money] for their loan." but no money change on the player. Everything works normally if player has enough money to pay the loan back.

I'm using DynamicEconomy v.8.5 with PermissionEX v1.19.1.

**Comment by EmpathDemon** [comment]
To pile on to this, it would be great if we could hook into an event when loans default. I'd love to do nasty things like change group membership and revoke protected regions/chests. Perhaps even a cooldown period for taking out new loans after a default, which could be specified in the config.

**Comment by ksafin** [comment]
Ellox, this has been fixed in the recent versions with "debt".

EmpathDemon, I'll be working on making an API to hook into DE after the release of 1.0.
