### ISSUE TITLE
Error when parsing command

### ISSUE THREAD

**Issue by lt-royal-shrimp** [ksafin/DynamicEconomy#82]
i have a problem. 

in game the plugin works. i can buy and sell, set the prices and everything else. whoever, the moment i try /dynecon getupdate, or /dynecon info or a reload, it quits and say error in parsing of command. i have a picture of the screen if that would be of any help!

also, i am using Iconomy as my econ plugin! 

thanks in advance!

**Comment by ksafin** [comment]
Yeah, a screen or paste of the error would be helpful.

**Comment by ksafin** [comment]
Neither of the two commands you said in your post are real commands.

The error was because the second argument to the /dynecon command is an integer page number and you're passing strings.
