### ISSUE TITLE
Please add Some items :)

### ISSUE THREAD

**Issue by BONNe** [ksafin/DynamicEconomy#84]
Could you add please some items, like

GRASS
ENDDRAGONEGG

And fix BUCKET bug -> cannot sell it and did not find :(

Also with buy wood is problem-> buy junglewood (or other) and always get wood :(

**Comment by BONNe** [comment]
Some itemnames are funny.... like BROWNINK :D but it is cocoabean :)

**Comment by ksafin** [comment]
Ok, I added MANY Items in this latest update :)
