### ISSUE TITLE
IDs of damage value items change

### ISSUE THREAD

**Issue by Superboop** [ksafin/DynamicEconomy#89]
Ok, so when I first downloaded this, in the item.yml, the ID values of pine log was 17001, birch log was 17002, and so on.
Since 17001 didn't work, I changed it to 17:1, as someone has said.

But the ID changed; it suddenly became random numbers when I started the server. 17:1 became 1021, 17:2 became 1022, 263:1 became 15781. Furthermore when I attempt to sell it says "An internal error occured."

But there is no error on the log.

**Comment by ksafin** [comment]
Well, I don't know who suggested to change the ID of anything to 17:1 or etc, I have no clue what kind of weird behavior that could cause.

Is 17001 as an ID not working for you? Why? Are you trying to buy or sell according to the ID?

**Comment by ksafin** [comment]
Closed due to no response, may be re-opened if response is met, I can't seem to reproduce the error.
