### ISSUE TITLE
Async tasks error

### ISSUE THREAD

**Issue by megge** [ksafin/DynamicEconomy#9]
I get this logged by NoLagg Plugin. I guess DE works in the current state, too, but I may be good programming practise to fix that.
"'DynamicEconomy': This plugin is not properly shutting down its async tasks when it is being reloaded.  This may cause conflicts with the newly loaded version of the plugin"

**Comment by ksafin** [comment]
Added a line to onDisable() to cancel all plugin tasks;

This should fix this error; if not, please submit another ticket.

It'll be out in v .7.7
