### ISSUE TITLE
/buy and /sell command doesnt work and Error in console

### ISSUE THREAD

**Issue by MRCartm0n** [ksafin/DynamicEconomy#91]
When I use /buy or /sell for example /buy 1 1 then it says Purchase succesfull but I dont get the item and right after thois msg, I get this: A internal error occurred while attempting ...

Also getting this error: http://pastebin.com/UMcgWWHq

I'm also getting my console spammed with: "Taks DynamicEconomy generated a Expection"

I use newest Vault, Essentials Eco.

**Comment by ksafin** [comment]
It should work now. This was a locale problem I've had for a while and just now found the solution to :)
