### ISSUE TITLE
Price glitch

### ISSUE THREAD

**Issue by Kaitoshijo** [ksafin/DynamicEconomy#93]
When I do /price for any any item it shows the correct price that is in the items.yml. However, when you actually go into the store and do /buy for any item, the price is 0. If need I can link the items.yml and config.yml. I have not changed it for months though. The only recent change is updating to 8.5 from 8.31.

**Comment by ksafin** [comment]
I can't replicate this error; it's working fine for me.

Can you provide a link to your Items.yml, configs.yml?

Before you do that, if you make a brand new shop region, does this problem persist within that new region?

**Comment by Kaitoshijo** [comment]
I actually deleted all dynamic economy files and downloaded the .jar from
bukkit dev. When I did that I still had the issue. I have attached the 2
files. I am quite sure I am using the newest craftbukkit.jar. And I use
essentials/iConomy for my economy.

On Fri, Jun 8, 2012 at 6:29 PM, Kirill Safin <
reply@reply.github.com

**Comment by Kaitoshijo** [comment]
I guess attachments dont work so I put them on pastebin.com

http://pastebin.com/A6P52jkU

http://pastebin.com/c8YzqVZ9

**Comment by ksafin** [comment]
So is this error everywhere or only in regions?

Like, if you disable regions and try, does it work?

**Comment by Kaitoshijo** [comment]
I will test that now

On Sat, Jun 9, 2012 at 4:15 PM, Kirill Safin <
reply@reply.github.com

**Comment by Kaitoshijo** [comment]
I turned off regions and it worked. I turned them back on and put the
original regions back up. And it still works. Thank you so much.

**Comment by ksafin** [comment]
You're welcome!
