### ISSUE TITLE
Config Wont generate (Error pastie attached)

### ISSUE THREAD

**Issue by Master-Zangetsu** [ksafin/DynamicEconomy#96]
http://pastie.org/4033188

**Comment by ksafin** [comment]
Hmm, this is VERY odd, because it's saying that a legitimate constructor isn't being found.

Can you provide me as much information as possible about your system, and if this error is still persisting? Also, DE version, Vault version, as well as Eco & version?

**Comment by Master-Zangetsu** [comment]
vault is the latest version and so is iconomy and ive just updated to the new DE and having the same problem.

i do also have essentials but its economy is deactivated properly

ive included a new pastie that was the error produced in the new version of DE

http://pastie.org/4066411 

it seems to be identical to the last one
