### ISSUE TITLE
No price change, new price message

### ISSUE THREAD

**Issue by EmpathDemon** [ksafin/DynamicEconomy#97]
I'm not sure if this is a bug or a feature request, but when the price of an item doesn't change, there should not be a "New Price" (or random event) global message.

**Comment by ksafin** [comment]
Please clarify, I don't know what you mean.

**Comment by EmpathDemon** [comment]
I'm looking at a message now that says:

New Price of COOKEDCHICKEN is $4.0 (0.0)

It's a pointless message, because the price didn't change, and just results in spam. The same thing should apply to Random Events that don't change the price (either from hitting the floor or the ceiling).

**Comment by ksafin** [comment]
Ah, gotcha. I'll get right on it.

**Comment by ksafin** [comment]
Functionality has been added; you'll no longer be bothered :)
