### ISSUE TITLE
Suggestion and bug

### ISSUE THREAD

**Issue by xdeathoreox** [ksafin/DynamicEconomy#99]
BUG: 

When you type /buy grass, it doesn't give anything, but it says you have bought 1 grass for x amount. And it even takes it out of your balance. But, you never got a grass block. Also, I gave myself 1 grass block, tried to sell it and it said I didn't have 'GRASS'. So I couldn't sell it. Now I don't know if it's like this with the other added items but it is with the grass block. 

I set the price,floor and ceiling. I also added stock and was in a economy zone.

SUGGESTION:

Make this work with CORE (http://dev.bukkit.org/server-mods/core/), it's basically essentials but as everything built into one file/jar. When I say work with, I mean make it work with the economy system built into it.

**Comment by ksafin** [comment]
Do all the other new items work and it's just a grass issue, or do no items work at all?

As for your suggestion - Since I use Vault to access economies, that's more of a suggestion for their end; they support iConomy, BOSEconomy, and Essentials Eco.

**Comment by xdeathoreox** [comment]
I'm positive it's with all the new items. I think it's because you normally can't get them unless you use silk touch or a client mode/creative mode. I just tried it with a mob spawner and it did the same thing.

**Comment by xdeathoreox** [comment]
whoops, wrong button

ignore the closed issue

**Comment by ksafin** [comment]
OK, then I know whats up.

Currently, when there's a DE update with new items, you need to back up your Items.yml, delete it, and then DE will re-generate a new one with the new items in it. Right now, yours doesn't have the new items in it, whereas the code itself recognizes the new items and feels OK taking it from you.

What I suggest you do is backup Items.yml, delete the original, restart so a new one generates, and then copy over your respective settings from the backup.

I know this is a hassle, and I plan to make it easier in coming updates.

**Comment by xdeathoreox** [comment]
Ok, thanks for helping. And I asked the CORE dev to make it work with this, he said it was DE problem because there are DE errors when buying an item.

**Comment by ksafin** [comment]
No problem, glad you got it working (you did, right?).

Uhhh, that's not really accurate.
Since I use Vault to access the economy the server uses, I have absolutely NOTHING to do with hooking into economy plugins. That's all on Vault. I simply get the economy from vault and commit transactions.
